# Simple Makefile for .rsrc Python tool tests

norsrc: main.cpp
	CL /Fe".\testnorsrc.exe" /Fo".\testnorsrc.obj"  /EHsc main.cpp

rsrc: main.cpp
	CL /Fo"test.obj"  /EHsc /c main.cpp
	RC VERSIONINFO.rc
	LINK test.obj VERSIONINFO.res

clean:
	del *.obj *.exe *.res
