# This workflow produces variables ingested by other workflows
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent

on:
  workflow_call:
    outputs:
      python-versions: 
        description: 'Python Versions'
        value: ${{ jobs.produce.outputs.python-versions }}
      node-versions: 
        description: 'Node Versions'
        value: ${{ jobs.produce.outputs.node-versions }}

env:
  pythonversions: "['3.11', '3.10', '3.9']" # Keep Python Versions in descending order
  nodeversions: "['19']"

jobs:
  produce:
    name: Produce

    runs-on: ubuntu-latest

    outputs:
      python-versions: ${{ steps.set-python-versions.outputs.VERSION }}
      node-versions: ${{ steps.set-node-versions.outputs.VERSION }}

    steps:
    - name: Produce Python Version
      id: set-python-versions
      run: echo "VERSION=$pythonversions" >> $GITHUB_OUTPUT

    - name: Produce Node Version
      id: set-node-versions
      run: echo "VERSION=$nodeversions" >> $GITHUB_OUTPUT
