# File markdown-lint-steps.yml
#
# These steps assume the spell-test-steps.yml have already
# been run to set the NodeTool version.
#
# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  none: ''

steps:
- script: npm install -g markdownlint-cli
  displayName: "Install markdown linter"

- script: markdownlint "**/*.md"
  displayName: "Lint md files"
